[pytest]
DJANGO_SETTINGS_MODULE = whrblog.settings
python_files = test_*.py tests.py
pythonpath = .
testpaths =
    core/tests
    apps/accounts/tests
    apps/blog/tests
    apps/comments/tests
addopts = --tb=short --reuse-db