from django.urls import path

from .api_views import (
    AvatarUploadAPIView,
    ChangeEmailAPIView,
    ChangePasswordAPIView,
    ForgetPasswordAPIView,
    ForgetPasswordEmailCodeAPIView,
    LoginAPIView,
    LogoutAPIView,
    RegisterAPIView,
    ResendVerifyEmailAPIView,
    SendChangeEmailCodeAPIView,
    SendRegisterCodeAPIView,
    UserInfoAPIView,
    VerifyEmailAPIView,
)

app_name = "accounts"

urlpatterns = [
    path(r'api/register',
         RegisterAPIView.as_view(),
         name='api-register'),
    path(r'api/send_register_code',
         SendRegisterCodeAPIView.as_view(),
         name='api-send-register-code'),
    path(r'api/login',
         LoginAPIView.as_view(),
         name='api-login'),
    path(r'api/logout',
         LogoutAPIView.as_view(),
         name='api-logout'),
    path(r'api/user',
         UserInfoAPIView.as_view(),
         name='api-user'),
    path(r'api/verify_email',
         VerifyEmailAPIView.as_view(),
         name='api-verify-email'),
    path(r'api/resend_verify_email',
         ResendVerifyEmailAPIView.as_view(),
         name='api-resend-verify-email'),
    path(r'api/forget_password',
         ForgetPasswordAPIView.as_view(),
         name='api-forget-password'),
    path(r'api/forget_password_code',
         ForgetPasswordEmailCodeAPIView.as_view(),
         name='api-forget-password-code'),
    path(r'api/change_password',
         ChangePasswordAPIView.as_view(),
         name='api-change-password'),
    path(r'api/change_email',
         ChangeEmailAPIView.as_view(),
         name='api-change-email'),
    path(r'api/send_change_email_code',
         SendChangeEmailCodeAPIView.as_view(),
         name='api-send-change-email-code'),
    path(r'api/upload_avatar',
         AvatarUploadAPIView.as_view(),
         name='api-upload-avatar'),
]